### ISSUE TITLE
VERY Basic usage help needed. 

### ISSUE THREAD

**Issue by jacksnodgrass** [ChrisMicro/mcurses#11]
For the slow kids... how exactly do you get this code incorporated into an Arduino project?  I copied: 
```
void Arduino_putchar(uint8_t c)
{
  Serial.write(c);
}
```

and: 

```
    setFunction_putchar(Arduino_putchar); // tell the library which output channel shall be used

    initscr();                  // initialize mcurses

    move (11, 15);              // set cursor position
    addstr ("Hello, World");    // show text
```

into a sketch and when I verified it, it said: 
```
/tmp/ccJK8OE6.ltrans0.ltrans.o: In function `setup':
/home/jack/arduino_stuff/blink/blink.ino:64: undefined reference to `setFunction_putchar'
/home/jack/arduino_stuff/blink/blink.ino:66: undefined reference to `initscr'
/home/jack/arduino_stuff/blink/blink.ino:68: undefined reference to `move'
/home/jack/arduino_stuff/blink/blink.ino:69: undefined reference to `addstr'
collect2: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1
```
which I understand...  am I supposed to comple the .c stuff from the src dir... or just put it somewhere and it gets magically compiled? I don't understand ( beginner with arduino software ) how to incorporate this 'mcurses' stuff with my existing code that I am using with the Arduino IDE.  

I am sure it's basic info for some of you... but not others.....

**Comment by ChrisMicro** [comment]
I assume you forgot the "include" at the beginning of the code:

#include "mcurses.h"

The best thing would be looking into the example folder and trying to compile one of the examples.

**Comment by jacksnodgrass** [comment]
I am used to having to compile .c code....  for this, all I needed to do was copy the *.c and *.h files to my Arduino Directory where my .ino file was and the system did everything for me.... it was too easy... I thought I was going to have to do more. Still think something to that effect should be put in your readme... but I'm good now. Thanks

**Comment by ChrisMicro** [comment]
The code is an Arduino Library. The way to include and handle Arduino Libraries is standardized. 
You should place this code in the Arduino library folder than the examples appear in the menue and can be compiled.

See user created libraries here:
[Arduino Libraries](https://docs.arduino.cc/hacking/software/Libraries)
